css-modules/css-modulesify

README.md
index.js
package.json

@joshgillies @rtsao please let me know if you think this should be approached differently, or have other ideas.
Notable changes:
- `--css` plugin option is required (destination css file)
- I've removed the `.toString` export, since css will be written to a file instead of being included in the js bundle (for consistency with the webpack implementation).
Once we've done some more testing on this we'll merge and then will need to upgrade https://github.com/css-modules/browserify-demo

Browserify plugin

---

index.js

Previously, CSS builds were only written out once and watchify would have to be restarted to trigger a new rebuild. This rewrites the CSS file on each call to `b.bundle()`, taking into account that watchify won't be re-transforming every CSS file every time.
Thanks! :)

Ensure css-modulesify plays nice with watchify

---

README.md
index.js
package.json

Placeholder PR to add support for configurable PostCSS Plugins.
Ref: #12

Add user configurable PostCSS plugins.

---

index.js

Turns out, post-css plugins are functions, not objects when already
setup.

fix: already setup plugins detected correctly

---

index.js

This allows css-moduleify to be installed in a different directory than
the post-css plugins and still allow them to be found.

add: plugin paths now found relative to cwd

---

index.js
package.json

This fixes the issue noted in #15.  Depends on an update to `postcss-modules-scope` (but it might make more sense for this to become the default behavior).

append a hash of the css source to scoped classnames

---

index.js

b/c sometimes, the default doesn’t work out!

fix: allow users to override generateScopedName

---

index.js

Two things:
1) Reverting back to browserify's original `bundle` method. This method is only intended to take a singular argument (a callback in this case).
2) `stream.on('end', function () {})` creates a race condition. Using a callback in the bundle method instead to resolve this.

Fix race condition

---

README.md
index.js

Although we've discussed further improvements to the plugin architecture in #26 I'd like to add this new option in the meantime, since it's completely opt-in and doesn't affect existing behaviour.
@joshgillies pls take a look and merge if you're happy with it.

new option and updated readme

---

README.md
index.js

This adds an optional `json` config (or `--json` via CLI).  If provided, all export tokens are written to a json file (indexed by source css filename).
I haven't tried using this but wanted to see if people are interested in trying it. Could potentially open up a way to use css-modules with non-js backends.

Generate a manifest json of export tokens

---

README.md

Looks like most cases of the word "transform" were changed to "plugin" upon merging #10 back in June, but the top-level description (not reflected in this PR, will have to be manually changed by project owner) and the first description in the README still list it as "transform".

Update README to reflect change from transform to plugin

---

index.js
package.json
tests/cache.js

Previously, the caches were re-initialized on every plugin initialization.
This caused an incompatibility with other tools like rebundler or
persistify.
This change keeps the original intent of creating caches when the plugin is
initialized, but ensures the process keeps the caches instead of the plugin
instance itself. It’s not really possible to have a cache conflict since
they’re keyed by file.
Fixes #32

Ensure caches are persisted

---

.eslintignore
.eslintrc
index.js
package.json
tests/cases/compose-node-module/main.js
tests/cases/import-node-module/main.js
tests/index.js

Adds, configures, and fixes problems for eslint. I tried to configure it to match the code style already present.

Add eslint

---

index.js

I was having this issue when I've miss-typed a class name and `css-modulesify` would silently stop working when using `watchify`.
My `package.json` scripts object:
```json
"scripts": {
"start": "http-server -s & npm run watch-coffee",
"build": "npm run build-coffee",
"watch-coffee": "watchify -v -p [ css-modulesify -o dist/starterkit.css ] -t [ hbsfy -e thtml ] -t coffeeify starterkit/src/app.coffee -o dist/starterkit.js",
"build-coffee": "browserify -p [ css-modulesify -o dist/starterkit.css ] -t [ hbsfy -e thtml ] -t coffeeify starterkit/src/app.coffee -o dist/starterkit.js"
},
```
With this change error will emit back to watchify and recover will work as well.

Emit error on stream.

---

README.md
index.js
tests/index.js

Update to add a new `generateScopedName` option.
By default it uses `generateLongName`, which is similar to the current behaviour.  But if `NODE_ENV=production` it will use a shorter name (file hash + line number).
This also means a cleaner API, setting `generateScopedName` directly on `css-modulesify` rather than needing to reach in and set it as an option of the postcss plugin.

update to allow passing a generateScopedName func directly

---

index.js

Because we’re setting `tokensByFile` before and after an async action,
and many of these actions can happen at the same time, there’s a race
condition where the incorrect `tokensByFile` can be set.
This accomplishes the same desire for caching by just keeping the loader
for every file since the loader already caches `tokensByFile`, and
prevents the race condition.

fix a race-condition with tokensByFile

---

README.md
index.js
tests/cases/multiple-js-files/expected.css
tests/cases/multiple-js-files/main.js
tests/index.js
tests/stream-output.js

The `bundle` now emits a `’css stream’` event. Users can listen to this and
get a stream of the compiled CSS.
I’m not a super big fan of this API, but I couldn’t think of a better way
to give access to the stream.
fixes #17

fix #17: add a stream output option

---

package.json

Just tying up a minor detail before a potential release.
Also, so I can `"css-modulesify": "git://github.com/bcomnes/css-modulesify.git#values-support"` this afternoon prior to release.
UPDATE:  Seems to be working really well from some light use this afternoon.

Update "css-modules-loader-core" to "^1.0.0" on #47: values-support

---

index.js

I found that if we didn't key the internal source caches in css-modulesify by something identifiable per build pipe (like the expected css output file name), we'd soon find unexpected css scattered across our our screens.
This issue should have only affected larger build setups that need to start several instances of browserify in a single build.

allow parallel bundles to isolate their css source caches

---

index.js
tests/cases/compose-from-shared/expected.css
tests/cases/compose-from-shared/main.js
tests/cases/compose-from-shared/shared.css
tests/cases/compose-from-shared/styles-1.css
tests/cases/compose-from-shared/styles-2.css

In certain cases we will get duplicates, and this causes issues with `composes`.
@joeybaker and @loklaan can you please take a look here as this affects some code in your recent pull requests.
I've also added a new test case `compose-from-shared` which previously fails, but passes with this PR.

Fix duplicate rules

---

cmify.js
file-system-loader.js
index.js
package.json
tests/cases/compose-node-module/expected.css
tests/index.js

+ using a different kind of tranform that ends the stream correctly
+ inject require statements for composed css modules, so that they are
added to browserify's dependency graph
+ clear token cache so that we can rebuild the parts that change

Updates to make watchify work

---

index.js

Fixes a bug where postcss plugins were being added to the file system loader _before_ they were actually ready
Closes #65

Fix PostCSS Plugins bug

---

.gitignore
cmify.js
index.js

Fixes #76 
(also included some code style fixes as suggested by the linter)

Fix separation of loaders

---

index.js

There were no errors being thrown in the console when bundling with browserify which broke the build process and prevented watchify from rebuilding.

Fix bug where browserify didn't emit error

---

index.js

Add ability to load already configured plugins like cssnext(options), which returns processor object, not a function.

load plugins by name only if a string is used

---

README.md
index.js

Use browserify basedir as a fallback for rootDir

---

file-system-loader.js

Pass correct 'from' parameter to postcss for files which resolved via `nodeResolve.sync`
Incorrect source path leads to wrong names which postcss-plugin-scope generates for example

Pass correct `from` arg for resolved files

---

README.md
index.js
tests/stream-output.js

Previously, the event would only get emitted on the first run. This is a
problem for watchify-like environments.
Note: this is a breaking change.

Fix: correctly emit 'css stream'

---

README.md

added info about the global flag to readme

---

file-system-loader.js

traces in current implementation can't be correct, because trace doesn't count dependencies
in case if dependency already loaded.

use dependency graph for resolving overall order instead of traces

---

README.md
index.js

We have an `after` parameter, adding a `before` parameter.

Run postcss plugins before the default

---

index.js

This PR moves the CSS and JSON emitting to the `pack` stage of the Browserify pipeline, similar to how `factor-bundle` works. This change enables other plugins to listen to the `css stream` event and react within the Browserify pipeline as well.
This PR also uses `module.parent.require` to pull in plugins that were given by string. This has no effect in normal situations, but allows this library to be linked in via `npm link`.

Emit on pack stage of pipeline

---

index.js

There's currently no way to pass in the `global` option via the `browserify` command line. Ie:
``` bash
$ browserify -p [ css-modulesify -g -o bundle.css ] index.js -o bundle.js
```
Where `index.js` is a file that requires a CSS module from within `node_modules`. Eg:
``` js
const maxWidths = require('tachyons-max-widths');
```
This PR fixes this issue.

allow global option via command line

---

README.md
cmify.js
index.js
tests/cache.js
tests/index.js

Currently when running css-modulesify first time passed postcss plugins are cached in loader and the subsequent runs in the same process but with different set of plugins result in using cached plugins. The only workaround is to reload module with `delete require.cache[require.resolve('css-modulesify')];`.
This is happening because of persisting cache globally that was made because `cache` option passed to browserify [is forwarded](https://github.com/substack/node-browserify/issues/1004#issuecomment-65747255) to [module-deps](https://github.com/substack/module-deps/blob/master/index.js) where it's filled with record for each module (record for css module contains javascript code generated with `cmify.js`). So without persisting tokens and loader between runs when using browserify `cache` …

Do not use global cache
